include ../../Config/GNUmakefile.Web

HTML_STYLESHEET=http://www.omegahat.org/OmegaTech.css

RD_FILES=$(wildcard ../man/*.Rd)
HTML_DOC_FILES=$(RD_FILES:%.Rd=docs/%.html)
htmlDocs: $(HTML_DOC_FILES)







